apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}  # Dynamically set the size
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com              # Use the EFS CSI driver
    volumeHandle: {{ .Values.efs.volumeHandle }}  # EFS file system ID from values.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  namespace: {{ .Values.namespace }}       # Dynamically set the namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc                 # Reference the same storage class
  resources:
    requests:
      storage: {{ .Values.storage.size }}   # Dynamically set the requested size
