apiVersion: v1
kind: Service
metadata:
  name: example-app-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: example-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

